#! /bin/bash

case $(uname) in
    Linux)
	CHROME=/opt/google/chrome/chrome
	;;
    Darwin)
	CHROME=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
	;;
    *)
	;;
esac

# export NACL_EXE_STDOUT=/tmp/stdout.log
# export NACL_EXE_STDERR=/tmp/stderr.log
export NACL_EXE_STDOUT=/tmp/nacl.log
export NACL_EXE_STDERR=/tmp/nacl.log
export NACL_DEBUG_ENABLE=1

#"$CHROME" --enable-nacl --enable-nacl-debug --no-sandbox --disable-hang-monitor localhost:5103
"$CHROME" --enable-nacl --enable-nacl-debug --no-sandbox --disable-hang-monitor
